# -*- coding: utf-8 -*-
"""Aula 1 - Imersão Dados com Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MlmWOlJ_d2dVyGR9hiyMdScHG1bHaOfS

# **Aula 1 - Análise de Dados com Pandas**

---
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head(10)

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]
print("Linhas:", linhas)
print("Colunas:", colunas)

df.columns

renomear_colunas = {
    'ano_trabalho': 'ano',
    'nivel_experiencia': 'senioridade',
    'tipo_emprego': 'contrato',
    'cargo': 'cargo',
    'salario': 'salario',
    'moeda_salario': 'moeda',
    'salario_em_usd': 'usd',
    'residencia_empregado': 'residencia',
    'taxa_remoto': 'remoto',
    'localizacao_empresa': 'empresa',
    'tamanho_empresa': 'tamanho_empresa'
}
df.rename(columns=renomear_colunas, inplace=True)
df.columns

df['senioridade'].value_counts()

df['contrato'].value_counts()

df['remoto'].value_counts()

df['tamanho_empresa'].value_counts()

df['senioridade'] = df['senioridade'].replace({
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
})

df['senioridade'].value_counts()

df['contrato'] = df['contrato'].replace({
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelancer'
})

df['contrato'].value_counts()

df['tamanho_empresa'] = df['tamanho_empresa'].replace({
    'M': 'Média',
    'L': 'Grande',
    'S': 'Pequena'
})

df['tamanho_empresa'].value_counts()

df['remoto'] = df['remoto'].replace({
    0: 'Presencial',
    100: 'Remoto',
    50: 'Híbrido'
})

df['remoto'].value_counts()

df.head(10)

df.describe(include='object')

df.describe()