# -*- coding: utf-8 -*-
"""Aula 0 de Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPzWoIVL_G7PZPzB0upsNxVP71Blm5Up
"""

'cinza'

'Naian'

print('Boas Vindas a Aula de Python')

print('Boas Vindas')

CORFAVORITA = 'vermelho'

"""Formas de escrever o código
camelCase
PascalCase
snake_case
kebab-case
"""

nome = 'Naian'
cor_favorita = 'vermelho'

print( nome, cor_favorita)

saldo = 5000

saldo

saldo = saldo + 2000

saldo

print('Saldo na sua conta: R$ ', saldo)

saldo -= 500

print('Saldo na sua conta: R$ ', saldo)

saldo *= 2

print('Saldo na sua conta: R$ ', saldo)

import this

idade = 18
#Se idade for maior que 18
if idade >= 18:
#pode dirigir
  print("Você pode dirigir")
#se não
else:
#não pode dirigir
  print("Você não pode dirigir")